package com.tx5d.t.activitytool;

import java.util.ArrayList;
import java.util.List;

/**
 * Created by Mre on 2017/9/29.
 */

public class DNFHelper {
        public static List<ServerSelect> GETServerSelect()
        {
            List<ServerSelect> Server = new ArrayList<ServerSelect>();
            List<ServerSelect> tmp=null;
            tmp=new ArrayList<ServerSelect>();
            tmp.add(new ServerSelect( "广东一区", "1",null));
            tmp.add(new ServerSelect( "广东二区", "15",null));
            tmp.add(new ServerSelect( "广东三区", "22",null));
            tmp.add(new ServerSelect( "广东四区", "45",null));
            tmp.add(new ServerSelect( "广东五区", "52",null));
            tmp.add(new ServerSelect( "广东六区", "65",null));
            tmp.add(new ServerSelect( "广东七区", "71",null));
            tmp.add(new ServerSelect( "广东八区", "81",null));
            tmp.add(new ServerSelect( "广东九区", "89",null));
            tmp.add(new ServerSelect( "广东十区", "98",null));
            tmp.add(new ServerSelect( "广东十一区", "105",null));
            tmp.add(new ServerSelect( "广东十二区", "126",null));
            tmp.add(new ServerSelect( "广东十三区", "134",null));
            Server.add(new ServerSelect("广东","21",tmp));
            tmp=new ArrayList<ServerSelect>();
            tmp.add(new ServerSelect( "福建一区", "14",null));
            tmp.add(new ServerSelect( "福建二区", "44",null));
            tmp.add(new ServerSelect( "福建3/4区", "80",null));
            Server.add(new ServerSelect("福建", "33",tmp));
            tmp=new ArrayList<ServerSelect>();
            tmp.add(new ServerSelect( "浙江一区", "11",null));
            tmp.add(new ServerSelect( "浙江二区", "21",null));
            tmp.add(new ServerSelect( "浙江三区", "55",null));
            tmp.add(new ServerSelect( "浙江4/5区", "84",null));
            tmp.add(new ServerSelect( "浙江六区", "116",null));
            tmp.add(new ServerSelect( "浙江七区", "129",null));
            Server.add(new ServerSelect("浙江", "30",tmp));
            tmp=new ArrayList<ServerSelect>();
            tmp.add(new ServerSelect( "北京一区", "2",null));
            tmp.add(new ServerSelect( "北京2/4区", "35",null));
            tmp.add(new ServerSelect( "北京三区", "72",null));
            Server.add(new ServerSelect("北京", "22",tmp));
            tmp=new ArrayList<ServerSelect>();
            tmp.add(new ServerSelect( "上海一区", "3",null));
            tmp.add(new ServerSelect( "上海二区", "16",null));
            tmp.add(new ServerSelect( "上海三区", "36",null));
            tmp.add(new ServerSelect( "上海4/5区", "93",null));
            Server.add(new ServerSelect("上海", "23",tmp));
            tmp=new ArrayList<ServerSelect>();
            tmp.add(new ServerSelect( "四川一区", "4",null));
            tmp.add(new ServerSelect( "四川二区", "26",null));
            tmp.add(new ServerSelect( "四川三区", "56",null));
            tmp.add(new ServerSelect( "四川四区", "70",null));
            tmp.add(new ServerSelect( "四川五区", "82",null));
            tmp.add(new ServerSelect( "四川六区", "107",null));
            Server.add(new ServerSelect("四川", "24",tmp));
            tmp=new ArrayList<ServerSelect>();
            tmp.add(new ServerSelect( "湖南一区", "5",null));
            tmp.add(new ServerSelect( "湖南二区", "25",null));
            tmp.add(new ServerSelect( "湖南三区", "50",null));
            tmp.add(new ServerSelect( "湖南四区", "66",null));
            tmp.add(new ServerSelect( "湖南五区", "74",null));
            tmp.add(new ServerSelect( "湖南六区", "85",null));
            tmp.add(new ServerSelect( "湖南七区", "117",null));
            Server.add(new ServerSelect("湖南", "25",tmp));
            tmp=new ArrayList<ServerSelect>();
            tmp.add(new ServerSelect( "山东一区", "6",null));
            tmp.add(new ServerSelect( "山东2/7区", "37",null));
            tmp.add(new ServerSelect( "山东三区", "59",null));
            tmp.add(new ServerSelect( "山东四区", "75",null));
            tmp.add(new ServerSelect( "山东五区", "78",null));
            tmp.add(new ServerSelect( "山东六区", "106",null));
            Server.add(new ServerSelect("山东", "26",tmp));
            tmp=new ArrayList<ServerSelect>();
            tmp.add(new ServerSelect( "江苏一区", "7",null));
            tmp.add(new ServerSelect( "江苏二区", "20",null));
            tmp.add(new ServerSelect( "江苏三区", "41",null));
            tmp.add(new ServerSelect( "江苏四区", "53",null));
            tmp.add(new ServerSelect( "江苏5/7区", "79",null));
            tmp.add(new ServerSelect( "江苏六区", "90",null));
            tmp.add(new ServerSelect( "江苏八区", "109",null));
            Server.add(new ServerSelect("江苏", "27",tmp));
            tmp=new ArrayList<ServerSelect>();
            tmp.add(new ServerSelect( "湖北一区", "9",null));
            tmp.add(new ServerSelect( "湖北二区", "24",null));
            tmp.add(new ServerSelect( "湖北三区", "48",null));
            tmp.add(new ServerSelect( "湖北四区", "68",null));
            tmp.add(new ServerSelect( "湖北五区", "76",null));
            tmp.add(new ServerSelect( "湖北六区", "94",null));
            tmp.add(new ServerSelect( "湖北七区", "115",null));
            tmp.add(new ServerSelect( "湖北八区", "127",null));
            Server.add(new ServerSelect("湖北", "28",tmp));
            tmp=new ArrayList<ServerSelect>();
            tmp.add(new ServerSelect( "华北一区", "10",null));
            tmp.add(new ServerSelect( "华北二区", "19",null));
            tmp.add(new ServerSelect( "华北三区", "54",null));
            tmp.add(new ServerSelect( "华北四区", "87",null));
            Server.add(new ServerSelect("华北", "29",tmp));
            tmp=new ArrayList<ServerSelect>();
            tmp.add(new ServerSelect( "西北一区", "12",null));
            tmp.add(new ServerSelect( "西北2/3区", "46",null));
            Server.add(new ServerSelect("西北", "31",tmp));
            tmp=new ArrayList<ServerSelect>();
            tmp.add(new ServerSelect( "东北一区", "13",null));
            tmp.add(new ServerSelect( "东北二区", "18",null));
            tmp.add(new ServerSelect( "东北3/7区", "23",null));
            tmp.add(new ServerSelect( "东北4/5/6区", "83",null));
            Server.add(new ServerSelect("东北", "32",tmp));
            tmp=new ArrayList<ServerSelect>();
            tmp.add(new ServerSelect( "西南一区", "17",null));
            tmp.add(new ServerSelect( "西南二区", "49",null));
            tmp.add(new ServerSelect( "西南三区", "92",null));
            Server.add(new ServerSelect("西南", "34",tmp));
            tmp=new ArrayList<ServerSelect>();
            tmp.add(new ServerSelect( "河南一区", "27",null));
            tmp.add(new ServerSelect( "河南二区", "43",null));
            tmp.add(new ServerSelect( "河南三区", "57",null));
            tmp.add(new ServerSelect( "河南四区", "69",null));
            tmp.add(new ServerSelect( "河南五区", "77",null));
            tmp.add(new ServerSelect( "河南六区", "103",null));
            tmp.add(new ServerSelect( "河南七区", "135",null));
            Server.add(new ServerSelect("河南", "35",tmp));
            tmp=new ArrayList<ServerSelect>();
            tmp.add(new ServerSelect( "广西一区", "28",null));
            tmp.add(new ServerSelect( "广西2/4区", "64",null));
            tmp.add(new ServerSelect( "广西三区", "88",null));
            tmp.add(new ServerSelect( "广西五区", "133",null));
            Server.add(new ServerSelect("广西", "36",tmp));
            tmp=new ArrayList<ServerSelect>();
            tmp.add(new ServerSelect( "江西一区", "29",null));
            tmp.add(new ServerSelect( "江西二区", "62",null));
            tmp.add(new ServerSelect( "江西三区", "96",null));
            Server.add(new ServerSelect("江西", "37",tmp));
            tmp=new ArrayList<ServerSelect>();
            tmp.add(new ServerSelect( "安徽一区", "30",null));
            tmp.add(new ServerSelect( "安徽二区", "58",null));
            tmp.add(new ServerSelect( "安徽三区", "104",null));
            Server.add(new ServerSelect("安徽", "38",tmp));
            tmp=new ArrayList<ServerSelect>();
            tmp.add(new ServerSelect( "辽宁一区", "31",null));
            tmp.add(new ServerSelect( "辽宁二区", "47",null));
            tmp.add(new ServerSelect( "辽宁三区", "61",null));
            Server.add(new ServerSelect("辽宁", "39",tmp));
            tmp=new ArrayList<ServerSelect>();
            tmp.add(new ServerSelect( "山西一区", "32",null));
            tmp.add(new ServerSelect( "山西二区", "95",null));
            Server.add(new ServerSelect("山西", "40",tmp));
            tmp=new ArrayList<ServerSelect>();
            tmp.add(new ServerSelect( "陕西一区", "33",null));
            tmp.add(new ServerSelect( "陕西2/3区", "63",null));
            Server.add(new ServerSelect("陕西", "41",tmp));
            tmp=new ArrayList<ServerSelect>();
            tmp.add(new ServerSelect( "广州1/2区", "34",null));
            Server.add(new ServerSelect("广州", "42",tmp));
            tmp=new ArrayList<ServerSelect>();
            tmp.add(new ServerSelect( "河北一区", "38",null));
            tmp.add(new ServerSelect( "河北2/3区", "67",null));
            tmp.add(new ServerSelect( "河北四区", "118",null));
            tmp.add(new ServerSelect( "河北五区", "132",null));
            Server.add(new ServerSelect("河北", "43",tmp));
            tmp=new ArrayList<ServerSelect>();
            tmp.add(new ServerSelect( "重庆一区", "39",null));
            tmp.add(new ServerSelect( "重庆二区", "73",null));
            Server.add(new ServerSelect("重庆", "44",tmp));
            tmp=new ArrayList<ServerSelect>();
            tmp.add(new ServerSelect( "黑龙江一区", "40",null));
            tmp.add(new ServerSelect( "黑龙江2/3区", "51",null));
            Server.add(new ServerSelect("黑龙江", "45",tmp));
            tmp=new ArrayList<ServerSelect>();
            tmp.add(new ServerSelect( "吉林1/2区", "42",null));
            Server.add(new ServerSelect("吉林", "46",tmp));
            tmp=new ArrayList<ServerSelect>();
            tmp.add(new ServerSelect( "云南一区", "120",null));
            tmp.add(new ServerSelect( "贵州一区", "122",null));
            tmp.add(new ServerSelect( "云贵一区", "124",null));
            Server.add(new ServerSelect("云贵", "277",tmp));
            tmp=new ArrayList<ServerSelect>();
            tmp.add(new ServerSelect( "天津一区", "121",null));
            Server.add(new ServerSelect("天津", "278",tmp));
            tmp=new ArrayList<ServerSelect>();
            tmp.add(new ServerSelect( "新疆一区", "123",null));
            Server.add(new ServerSelect("新疆", "281",tmp));
            tmp=new ArrayList<ServerSelect>();
            tmp.add(new ServerSelect( "内蒙古一区", "125",null));
            Server.add(new ServerSelect("内蒙", "538",tmp));
            tmp=new ArrayList<ServerSelect>();
            tmp.add(new ServerSelect( "体验一区", "99",null));
            tmp.add(new ServerSelect( "体验二区", "199",null));
            Server.add(new ServerSelect("体验服", "7016761",tmp));

            return Server;
        }

}



